version: "3"
volumes:
  dronedata:
services:
  drone-server:
    image: drone/drone:2
    environment:
      DRONE_AGENTS_ENABLED: "true"
      DRONE_GOGS_SERVER: "http://192.168.145.131:10880"
      DRONE_RPC_SECRET: "b7da2c13e0241670873f83b40795ddea"
      DRONE_SERVER_HOST: "192.168.145.131:9080"
      DRONE_SERVER_PROTO: "http"
      DRONE_USER_CREATE: "username:imooc,machine:false,admin:true,token:55f24eb3d61ef6ac5e83d550178638dc"
    restart: always
    container_name: drone-server
    ports:
      - 9080:80
      - 9443:443
    volumes:
      - dronedata:/data
  drone-runner:
    image: drone/drone-runner-docker:1
    environment:
      DRONE_RPC_PROTO: "http"
      DRONE_RPC_HOST: "192.168.145.131:9080"
      DRONE_RPC_SECRET: "b7da2c13e0241670873f83b40795ddea"
      DRONE_RUNNER_CAPACITY: "2"
      DRONE_RUNNER_NAME: "my-first-runner"
    ports:
      - 3000:3000
    restart: always
    container_name: drone-runner
    depends_on:
      - drone-server
    volumes:
      - /etc/docker/:/etc/docker
      - /var/run/docker.sock:/var/run/docker.sock